// const convert = require('xml-js');

export const Colors = {
    background: "#fff",
    text: "#6F7371",
    blue: "#487CE1",
    green: "#1EA66D",
}

export function getLatLng(lat, lng) {
    return {
        latitude: lat,
        longitude: lng,
        latitudeDelta: 0.06,
        longitudeDelta: 0.04,
    }
};

export const level_1_airports = {
    ZGGG : "Guangzhou Baiyun International Airport",
    KATL : "Hartsfield-Jackson Atlanta International Airport",
    // ZUUU : "Chengdu Shuangliu International Airport",
    KDFW : "Dallas/Fort Worth International Airport",
    ZBAA : "Beijing Capital International Airport",
    KDEN : "Denver International Airport",
    ZSSS : "Shanghai Hongqiao International Airport",
    RJTT : "Tokyo Haneda Airport",
    KORD : "O'Hare International Airport",
    KLAX : "Los Angeles International Airport",
    VIDP : "ndira Gandhi International Airport",
    OMDB : "Dubai International Airport",
    LTFM : "Istanbul Airport",
    MMMX : "Mexico City International Airport",
    // VVTS : "Tan Son Nhat International Airport",
    KMCO : "Orlando International Airport",
    SBGR : "São Paulo/Guarulhos International Airport",
    KSEA : "Seattle-Tacoma International Airport",
    UUEE : "Sheremetyevo International Airport",
    EDDF : "Frankfurt Airport",
    LEMD : "Madrid Barajas Airport",
    KJFK : "John F. Kennedy International Airport",
};

export const level_2_airports = {
    ZGGG : "Guangzhou Baiyun International Airport",
    KATL : "Hartsfield-Jackson Atlanta International Airport",
    ZUUU : "Chengdu Shuangliu International Airport",
    KDFW : "Dallas/Fort Worth International Airport",
    ZBAA : "Beijing Capital International Airport",
    KDEN : "Denver International Airport",
    ZPPP : "Kunming Changshui International Airport",
    ZSSS : "Shanghai Hongqiao International Airport",
    ZLXY : "Xi'an Xianyang International Airport",
    RJTT : "Tokyo Haneda Airport",
    KORD : "O'Hare International Airport",
    KLAX : "Los Angeles International Airport",
    VIDP : "ndira Gandhi International Airport",
    KCLT : "Charlotte Douglas International Airport",
    OMDB : "Dubai International Airport",
    LTFM : "Istanbul Airport",
    LFPG : "Charles de Gaulle Airport",
    EGLL : "Heathrow Airport",
    MMMX : "Mexico City International Airport",
    KPHX : "Phoenix Sky Harbor International Airport",
    VVTS : "Tan Son Nhat International Airport",
    KMCO : "Orlando International Airport",
    ZHCC : "Zhengzhou Xinzheng International Airport",
    RKPC : "Jeju International Airport",
    SBGR : "São Paulo/Guarulhos International Airport",
    KSEA : "Seattle-Tacoma International Airport",
    ZSNJ : "Nanjing Lukou International Airport",
    UUEE : "Sheremetyevo International Airport",
    ZGHA : "Changsha Huanghua International Airport",
    EDDF : "Frankfurt Airport",
    KIAH : "George Bush Intercontinental Airport",
    RKSS : "Gimpo International Airport",
    LEMD : "Madrid Barajas Airport",
    ZSAM : "Xiamen Gaoqi International Airport",
    VTBS : "Suvarnabhumi Airport",
    KJFK : "John F. Kennedy International Airport",
    KFLL : "Fort Lauderdale-Hollywood International Airport",
    KSFO : "San Francisco International Airport",
    // UUDD : "Moscow Domodedovo Airport",
    ZBAD : "Beijing Daxing International Airport"
};

export const level_3_airports = {
    ZGGG : "Guangzhou Baiyun International Airport",
    KATL : "Hartsfield-Jackson Atlanta International Airport",
    ZUUU : "Chengdu Shuangliu International Airport",
    KDFW : "Dallas/Fort Worth International Airport",
    ZGSZ : "Shenzhen Bao'an International Airport",
    // ZUCK : "Chongqing Jiangbei International Airport",
    ZBAA : "Beijing Capital International Airport",
    KDEN : "Denver International Airport",
    ZPPP : "Kunming Changshui International Airport",
    ZSSS : "Shanghai Hongqiao International Airport",
    ZLXY : "Xi'an Xianyang International Airport",
    RJTT : "Tokyo Haneda Airport",
    KORD : "O'Hare International Airport",
    // ZSPD : "Shanghai Pudong International Airport",
    KLAX : "Los Angeles International Airport",
    VIDP : "ndira Gandhi International Airport",
    // ZSHC : "Hangzhou Xiaoshan International Airport",
    KCLT : "Charlotte Douglas International Airport",
    OMDB : "Dubai International Airport",
    LTFM : "Istanbul Airport",
    LFPG : "Charles de Gaulle Airport",
    EGLL : "Heathrow Airport",
    MMMX : "Mexico City International Airport",
    KPHX : "Phoenix Sky Harbor International Airport",
    VVTS : "Tan Son Nhat International Airport",
    KMCO : "Orlando International Airport",
    ZHCC : "Zhengzhou Xinzheng International Airport",
    RKPC : "Jeju International Airport",
    EHAM : "Amsterdam Airport Schiphol",
    SBGR : "São Paulo/Guarulhos International Airport",
    KSEA : "Seattle-Tacoma International Airport",
    ZSNJ : "Nanjing Lukou International Airport",
    UUEE : "Sheremetyevo International Airport",
    ZGHA : "Changsha Huanghua International Airport",
    EDDF : "Frankfurt Airport",
    // KMIA : "Miami International Airport",
    KIAH : "George Bush Intercontinental Airport",
    RKSS : "Gimpo International Airport",
    LEMD : "Madrid Barajas Airport",
    ZSAM : "Xiamen Gaoqi International Airport",
    VTBS : "Suvarnabhumi Airport",
    KJFK : "John F. Kennedy International Airport",
    ZUGY : "Guiyang Longdongbao International Airport",
    ZJHK : "Haikou Meilan International Airport",
    KFLL : "Fort Lauderdale-Hollywood International Airport",
    KSFO : "San Francisco International Airport",
    ZBAD : "Beijing Daxing International Airport"
};