/* eslint-disable no-undef */
export const Colors = {
    background: "#fff",
    text: "#6F7371",
    blue: "#487CE1",
    green: "#1EA66D",
    red: "red",
    purple: "purple",
    barb: "#383838",
};

export const monthAbbr = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export const level_1_airports = [
    // Europe
    "LTFM",
    "LFPG",
    "UUEE",
    // Asia
    "ZBAA",
    "OMDB",
    "RJTT",
    "VHHH",
    "VIDP",
    "WIII",
    "VTBS",
    // NA
    "KLAX",
    "MMMX",
    "KMCO",
    "KSEA",
    "KJFK",
    // SA
    "SBGR",
    "SKBO",
    "SCEL",
    "SPJC",
    // Africa
    "FAOR",
    "HECA",
    "HAAB",
    "GMMN",
    "HKJK",
    "DNMM",
    // OCE
    "YSSY",
    "NZAA",
    // CA
    "CYYC",
    "CYWG",
];

export const level_2_airports = [
    // Europe
    "LTFM",
    "LFPG",
    "EHAM",
    "UUEE",
    "LEMD",
    // Asia
    "ZBAA",
    "OMDB",
    "RJTT",
    "VHHH",
    "ZSPD",
    "VIDP",
    "RKSI",
    "WIII",
    "WSSS",
    "VTBS",
    "VABB",
    "RPLL",
    // NA
    "KATL",
    "KDFW",
    "KDEN",
    "KORD",
    "KLAX",
    "MMMX",
    "KMCO",
    "KSEA",
    "KJFK",
    "KSLC",
    // SA
    "SBGR",
    "SKBO",
    "SCEL",
    "SBBR",
    "SPJC",
    "SAEZ",
    "SABE",
    // Africa
    "FAOR",
    "HECA",
    "HAAB",
    "FACT",
    "GMMN",
    "HKJK",
    "DNMM",
    "DTTA",
    // OCE
    "YSSY",
    "YMML",
    "YBBN",
    "NZAA",
    // CA
    "CYYC",
    "CYUL",
    "CYWG",
];

export const level_3_airports = [
    // Europe
    "LTFM",
    "LFPG",
    "EGLL",
    "EHAM",
    "UUEE",
    "EDDF",
    "LEMD",
    "LEBL",
    // Asia
    "ZBAA",
    "OMDB",
    "RJTT",
    "VHHH",
    "ZSPD",
    "VIDP",
    "RKSI",
    "WIII",
    "WSSS",
    "VTBS",
    "VABB",
    "RCTP",
    "RPLL",
    "VVTS",
    // NA
    "KATL",
    "KDFW",
    "KDEN",
    "KORD",
    "KLAX",
    "KLAS",
    "MMMX",
    "KMCO",
    "KSEA",
    "KJFK",
    "KSFO",
    "KMSP",
    "KSLC",
    "MMUN",
    // SA
    "SBGR",
    "SKBO",
    "SCEL",
    "SBBR",
    "SPJC",
    "SAEZ",
    "SABE",
    "SEQM",
    // Africa
    "FAOR",
    "HECA",
    "HAAB",
    "FACT",
    "GMMN",
    "DAAG",
    "HKJK",
    "DNMM",
    "DTTA",
    // OCE
    "YSSY",
    "YMML",
    "YBBN",
    "NZAA",
    // CA
    "CYYZ",
    "CYVR",
    "CYYC",
    "CYUL",
    "CYEG",
    "CYWG",
];

export const level_4_airports = [
    // Europe
    "LTFM",
    "LFPG",
    "EGLL",
    "EHAM",
    "UUEE",
    "EDDF",
    "LEMD",
    "LEBL",
    // Asia
    "ZBAA",
    "OMDB",
    "RJTT",
    "VHHH",
    "ZSPD",
    "VIDP",
    "RKSI",
    "WIII",
    "WSSS",
    "VTBS",
    "VABB",
    "RCTP",
    "RPLL",
    "VVTS",
    // NA
    "KATL",
    "KDFW",
    "KDEN",
    "KORD",
    "KLAX",
    "KCLT",
    "KLAS",
    "MMMX",
    "KPHX",
    "KMCO",
    "KSEA",
    "KMIA",
    "KIAH",
    "KJFK",
    "KSFO",
    "KMSP",
    "KDTW",
    "KBOS",
    "KSLC",
    "MMUN",
    "KBWI",
    "KSTL",
    "KSDF",
    // SA
    "SBGR",
    "SKBO",
    "SCEL",
    "SBBR",
    "SPJC",
    "SAEZ",
    "SABE",
    "SEQM",
    // Africa
    "FAOR",
    "HECA",
    "HAAB",
    "FACT",
    "GMMN",
    "DAAG",
    "HKJK",
    "DNMM",
    "DTTA",
    // OCE
    "YSSY",
    "YMML",
    "YBBN",
    "NZAA",
    // CA
    "CYYZ",
    "CYVR",
    "CYYC",
    "CYUL",
    "CYEG",
    "CYWG",
];

export const imageList = {
    "-DZ" : require('../assets/weather/-DZ.png'),
    "-DZRA" : require('../assets/weather/-DZRA.png'),
    "-FZDZ" : require('../assets/weather/-FZDZ.png'),
    // "-FZDZ" : require('../assets/weather/-FZDZ.png'),
    "-GR" : require('../assets/weather/-GR.png'),
    "-RA" : require('../assets/weather/-RA.png'),
    "-RASN" : require('../assets/weather/-RASN.png'),
    "-SHRA" : require('../assets/weather/-SHRA.png'),
    "-SHRASN" : require('../assets/weather/-SHRASN.png'),
    "-SHSN" : require('../assets/weather/-SHSN.png'),
    "-SN" : require('../assets/weather/-SN.png'),
    "+DZ" : require('../assets/weather/+DZ.png'),
    "+FZDZ" : require('../assets/weather/+FZDZ.png'),
    "+FZRA" : require('../assets/weather/+FZRA.png'),
    "+RA" : require('../assets/weather/+RA.png'),
    "+RASN" : require('../assets/weather/+RASN.png'),
    "+SHRA" : require('../assets/weather/+SHRA.png'),
    "+SHRASN" : require('../assets/weather/+SHRASN.png'),
    "+SHSN" : require('../assets/weather/+SHSN.png'),
    '+SN' : require('../assets/weather/+SN.png'),
    '+SS' : require('../assets/weather/+SS.png'),
    '+TSRA' : require('../assets/weather/+TSRA.png'),
    'BCFG' : require('../assets/weather/BCFG.png'),
    'BLDU' : require('../assets/weather/BLDU.png'),
    'BLSA' : require('../assets/weather/BLSA.png'),
    'BLSN' : require('../assets/weather/BLSN.png'),
    'BR' : require('../assets/weather/BR.png'),
    'DRSN' : require('../assets/weather/DRSN.png'),
    'DU' : require('../assets/weather/DU.png'),
    'DZ' : require('../assets/weather/DZ.png'),
    'DZRA' : require('../assets/weather/DZRA.png'),
    'FC' : require('../assets/weather/FC.png'),
    'FG' : require('../assets/weather/FG.png'),
    'FU' : require('../assets/weather/FU.png'),
    'FZDZ' : require('../assets/weather/FZDZ.png'),
    'FZFG' : require('../assets/weather/FZFG.png'),
    'FZRA' : require('../assets/weather/FZRA.png'),
    'GR' : require('../assets/weather/GR.png'),
    'HZ' : require('../assets/weather/HZ.png'),
    'IC' : require('../assets/weather/IC.png'),
    'MIFG' : require('../assets/weather/MIFG.png'),
    'PE' : require('../assets/weather/PE.png'),
    'PL' : require('../assets/weather/PL.png'),
    'PO' : require('../assets/weather/PO.png'),
    'PRFG' : require('../assets/weather/PRFG.png'),
    'RA' : require('../assets/weather/RA.png'),
    'RASN' : require('../assets/weather/RASN.png'),
    'SA' : require('../assets/weather/SA.png'),
    'SG' : require('../assets/weather/SG.png'),
    'SHRA' : require('../assets/weather/SHRA.png'),
    'SHRASN' : require('../assets/weather/SHRASN.png'),
    'SN' : require('../assets/weather/SN.png'),
    'SQ' : require('../assets/weather/SQ.png'),
    'SS' : require('../assets/weather/SS.png'),
    'TS' : require('../assets/weather/TS.png'),
    'TSGR' : require('../assets/weather/TSGR.png'),
    'TSRA' : require('../assets/weather/TSRA.png'),
    'VA' : require('../assets/weather/VA.png'),
    'VCFG' : require('../assets/weather/VCFG.png'),
    'VCSH' : require('../assets/weather/VCSH.png'),
    'VCSS' : require('../assets/weather/VCSS.png'),
    'VCTS' : require('../assets/weather/VCTS.png'),
    'VIRGA' : require('../assets/weather/VIRGA.png'),
};

export const barbList = {
    5 : null,
    10 : {
        top: -2.75,
        right: -12.5,
    },
    15 : {
        top: 4,
    },
    20 : {
        top: 1.25,
        right: -12.5,
    },
    25 : {
        top: 8,
    },
    30 : {
        top: 5.25,
        right: -12.5,
    },
    35 : {
        top: 12,
    },
    40 : {
        top: 9.25,
        right: -12.5,
    },
    45 : {
        top: 16,
    },
};

export const pennantList = {
    48 : {
        top: .5,
        right: -6,
        height: 7,
        transform: [
            { translateX: -6 / 2 },
            { rotateZ: "-90deg" },
            { translateX: 6 / 2 },
        ],
    },
    49 : {
        top: 4,
        right: -5,
        height: 3.5,
        transform: [
            { translateX: -6 / 2 },
            { rotateZ: "-90deg" },
            { translateX: 6 / 2 },
        ],
    },
    50 : {
        top: 2,
        height: 9,
        right: -10,
    },
    55 : {
        top: 8,
    },
    60 : {
        top: 5.25,
        right: -12.5,
    },
    65 : {
        top: 12,
    },
    70 : {
        top: 9.25,
        right: -12.5,
    },
    75 : {
        top: 16,
    },
    80 : {
        top: 13.25,
        right: -12.5,
    },
    85 : {
        top: 20,
    },
    90 : {
        top: 17.25,
        right: -12.5,
    },
};

export const wxString = {
    18 : ["FU", "VA", "BR", "MIFG", "DU", "VCFG", "-DZ", "DZ-RA", "-DZRA", "-DZ-RA"],
    17 : ["VIRGA", "VCSH"],
    15 : ["SA", "BLSA", "VCBLSA", "BLDU", "VCBLDU", "BLPY", "BCFG", "DZ", "-RA", "-RA-SN", "-RASN", "-DZ-SN", "-DZSN"],
    14 : ["HZ", "TS", "BLSN", "VCBLSN", "PRFG", "DZRA", "+DZRA", "DZ+RA", "+DZ+RA", "-SHSN"],
    12 : ["VCTS", "+DZ", "RA", "-SN", "-SH", "-SHRA"],
    10 : ["DRSN", "FG", "-FZDZ", "RASN", "SN", "SG", "IC", "SHSN", "-GS", "-SHGS", "TSRA", "TSSN", "TSPL"],
    8 : ["PO", "VCPO", "SS", "DRSA", "DS", "DRDU", "+RA", "+RASN", "RA+SN", "PL", "PE", "SHPL", "SHPE", "SH", "+SH", "SHRA", "+SHRA"],
    7 : ["-SHRASN", "-SHSNRA", "-SHRA-SN",  "-SHSN-RA", "+SHSN", "GS", "SHGS", "+GS", "+SHGS", "TSGR", "TSGS"],
    6 : ["SQ", "+SS", "+DS", "FZFG", "FZDZ", "+FZDZ", "-FZRA", "+RA+SN", "DZSN", "+SN"],
    5 : ["-GR", "-SHGR", "GR", "SHGR" ,"+GR", "+SHGR", "+TSRA", "+TSSN", "+TSPL"],
    4 : ["FZRA", "+FZRA", "+DZSN", "DZ+SN", "+DZ+SN", "SHRASN", "SHSNRA", "+SHRASN", "+SHSNRA"],
    3 : ["VCSS", "VCDS", "UP", "+TSGS", "+TSGR"],
    2 : ["FC", "+FC"],
}